[package]
name = "framelet"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "framelet_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "framelet"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
windows-capture = "1.4.4"
lazy_static = "1.4"
thiserror = "2.0.12"
windows = {version = "0.61.3", features = [
    "Foundation_Collections",
    "Devices_Enumeration",
    "Media_Capture",
    "Win32_Graphics_Gdi",
] }
tauri-plugin-dialog = "2"
tauri-plugin-decorum = "1.1.1"

[target."cfg(target_os = \"macos\")".dependencies]
cocoa = "0.26"
